### ISSUE TITLE
launcher v4

### ISSUE THREAD

**Issue by baptdev** [emmanuel-battesti/swarm-rescue#11]
Hi,

I’m having issues with the launcher in v4. Some attributes are missing or incorrectly declared in the maps:
- max_timestep_limit (I think it should be _time_step_limit)
- max_walltime_limit (I think it should be _real_time_limit)
- compute_score_health_returned

Because of this, the score_manager can't recognize:
- max_timestep_limit (expected: time_step_limit)
- max_walltime_limit (expected: real_time_limit)

Could you check and confirm the correct attribute names and update them if needed?

Thanks!

**Comment by emmanuel-battesti** [comment]
Trying to get last year's solution to work with this year's new version of swarm-rescue, v4? 
max_timestep_limit and max_walltime_limit are new. I can't find reference to _time_step_limit  in the version v4.
The code has changed and is not fully backwards compatible. I think it will take a bit of work to get it working again.
